
EXE=sudoku

.PHONY: all build check clean help

all: build

build:  
	@cd src && $(MAKE)

clean:
	@cd src && $(MAKE) clean
	@rm -f $(EXE)

help:
	@echo -e "Usage:"
	@echo -e " make [all]\t\tBuild"
	@echo -e " make build\t\tBuild the software"
	@echo -e " make clean\t\tRemove all files generated by make"
	@echo -e " make help\t\tDisplay this help"







